services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: crater-user
        uid: 1000
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - crater
    expose:
      - "9000"
    command: >
      sh -c "composer install --optimize-autoloader --no-interaction &&
            php-fpm"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - crater

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - crater

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - crater

networks:
  crater:
    driver: bridge
